### ISSUE TITLE
refactor: refactor API responses to meet the LGPD

### ISSUE THREAD

**Issue by hmartiins** [PeruibeTEC/Server#43]
# Purpose

We need to change the API responses to the new LGPD (General Data Protection Law), ideally the responses return only the user id, and nothing that can identify him, such as name, email, photo...

You must return the id via the JWT token sub, so if the unique identifier changes we won't need to change all the keys in the token.

**Comment by diogo-braz** [comment]
solved

**Comment by hmartiins** [comment]
LGTM!
